### ISSUE TITLE
License declaration withnot typo

### ISSUE THREAD

**Issue by nmartensen** [dirty-south-supercomputing/debian-gbp#1]
Hi,
https://github.com/dirty-south-supercomputing/debian-gbp/blob/507d6450ee3f962583cc4ddf3c024cf5922e1921/debian/copyright#L31

You might want to s/WITHnot/WITHOUT/ here?
Glad to see this in Debian!

**Comment by dankamongmen** [comment]
How the hell did that happen? Fixed. Thanks! e3be1cf
